language: php
git:
  depth: 1
php:
  - 7.2
before_install:
  - openssl aes-256-cbc -K $encrypted_1503264ce2c7_key -iv $encrypted_1503264ce2c7_iv -in deploy/deploy-key.enc -out deploy/deploy-key -d
  - rm deploy/deploy-key.enc
  - chmod 600 deploy/deploy-key
before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - mkdir -p build/logs
#script:
#  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
