language: php

git:
  depth: 1

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: eyKYB/Vydk33MbcTcWatQ31UqZOGhUugwxxSuzduldjLOWNjRRlQAJEeGnUunItbtD4Dpwh+pi3N3bVzwLpo97zU7Xe5KFJEqW3ZAmumpiWNKdYWemT0SJNDLeKzgY/a2RGJdBaUxSrHYjpalE9XOVlwl0BPIaEesI8bKfiIW8qoHM3tWT5Yu+Z+/ZeuQPQDfpMhGovc9MzjouveO1CeC9f8jn87F18Bv9g/cmxL7lLoNNrvycoakEhix4hDCchhJ6Ad+0wy/JeDlECmUVPVGHeZKwr5mgrvLPpyyyhbGwed7neDG3nGglygYm1fWRWSK/RU4l1S+GhRa+JMcoiq/GPKhixx0jIlEvFTMVn9H5Q4+ia3QvPWaGa6hkYF1gDQYc4JZ1+9Qjn4gSXTVHKwmjE63l+2Fr47cYmkw1yZFjr9mbmYEGfWETUUxfM6jHT56uEZvH7dpOLYrXTsqg79w0EtCwinPoog35+t2IQkX3UBDMOeYxd760rYc2rFzdPV7i7gTvru7lWb6QfijAgJc4p3HQEfwMNJlMfS+JvBpoeAzCeSwfsl1LBpf7dCTCyjuHPbnHFdgw0hGUyesYWCR1Pae+mDPmB/OAjebQGWDkVYs2QcYS8k8ZRiM7TWR3la2/iaTl5m4MKIvegLKEqBxrNsgPZI0LYlm877uLGONiA=
  app: serieslist
  on:
    repo: Zeizig/serieslist
  run:
    - php artisan migrate --force
